<?xml version="1.0"?>
<package format="3">
  <name>cartpole_description</name>
  <version>0.1.0</version>
  <description>CartPole URDF model</description>
  <maintainer email="student@uni.edu">student</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>xacro</depend>
  <depend>robot_state_publisher</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
