<?xml version="1.0"?>
<package format="3">
  <name>cartpole_gazebo</name>
  <version>0.1.0</version>
  <description>CartPole Gazebo launch and world files</description>
  <maintainer email="student@uni.edu">student</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cartpole_description</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>robot_state_publisher</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
